/**
 * Visit Model
 *
 * This model represents visits made by field employees to doctors
 *
 * Key features:
 * - Weekly visit enforcement: One visit per doctor per week (Mon-Fri)
 * - Required GPS location for proof of visit
 * - Required photo capture for verification
 * - Weekly tracking with W1D1, W2D3 format labels
 * - Hard limit on monthly quota (2x or 4x based on doctor's visitFrequency)
 */

const mongoose = require('mongoose');

const visitSchema = new mongoose.Schema(
  {
    // References
    doctor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Doctor',
      required: [true, 'Doctor is required'],
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User is required'],
    },

    // Visit timing
    visitDate: {
      type: Date,
      required: [true, 'Visit date is required'],
      default: Date.now,
    },
    visitType: {
      type: String,
      enum: ['regular', 'follow-up', 'emergency'],
      default: 'regular',
    },

    // Weekly tracking fields (critical for enforcement)
    // Note: These are auto-generated by pre-save hook, not required on input
    weekNumber: {
      type: Number,
      min: 1,
      max: 53,
    },
    weekOfMonth: {
      type: Number,
      min: 1,
      max: 5,
    },
    dayOfWeek: {
      type: Number,
      min: 1, // 1 = Monday
      max: 5, // 5 = Friday
    },
    weekLabel: {
      type: String, // "W1D1", "W2D3", etc.
    },
    monthYear: {
      type: String, // "2024-12"
    },
    yearWeekKey: {
      type: String, // "2024-W52" - ISO week format for unique constraint
    },

    // Location (optional — attached when available for extra verification)
    location: {
      latitude: {
        type: Number,
        min: -90,
        max: 90,
      },
      longitude: {
        type: Number,
        min: -180,
        max: 180,
      },
      accuracy: {
        type: Number, // GPS accuracy in meters
      },
      capturedAt: {
        type: Date,
        default: Date.now,
      },
    },

    // Photos (REQUIRED - minimum 1, maximum 10 for proof of visit)
    photos: {
      type: [
        {
          url: { type: String, required: true }, // S3 URL
          capturedAt: { type: Date, required: true },
          source: { type: String, enum: ['camera', 'gallery', 'clipboard'], default: 'camera' },
          thumbnailUrl: { type: String },
        },
      ],
      validate: {
        validator: function (arr) {
          return arr && arr.length >= 1 && arr.length <= 10;
        },
        message: 'Visits must have 1-10 photos as proof of visit',
      },
    },

    // Products discussed during visit
    productsDiscussed: [
      {
        product: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'CrmProduct',
        },
        presented: { type: Boolean, default: true },
        feedback: { type: String },
      },
    ],

    // Engagement types (maps to Excel CPT day sheet columns G-K)
    engagementTypes: {
      type: [String],
      enum: ['TXT_PROMATS', 'MES_VIBER_GIF', 'PICTURE', 'SIGNED_CALL', 'VOICE_CALL'],
      default: [],
    },

    // Visit details
    purpose: {
      type: String,
      maxlength: [500, 'Purpose cannot exceed 500 characters'],
    },
    doctorFeedback: {
      type: String,
      maxlength: [1000, 'Feedback cannot exceed 1000 characters'],
    },
    notes: {
      type: String,
      maxlength: [1000, 'Notes cannot exceed 1000 characters'],
    },
    duration: {
      type: Number, // Duration in minutes
      min: 1,
      max: 480, // Max 8 hours
    },

    // Status tracking
    status: {
      type: String,
      enum: ['completed', 'cancelled'],
      default: 'completed',
    },
    cancelReason: {
      type: String,
      maxlength: [500, 'Cancel reason cannot exceed 500 characters'],
    },

    // Next visit scheduling
    nextVisitDate: {
      type: Date,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Compound index to enforce ONE visit per doctor per week per user
visitSchema.index(
  { doctor: 1, user: 1, yearWeekKey: 1 },
  {
    unique: true,
    partialFilterExpression: { status: 'completed' },
  }
);

// Other indexes for performance
visitSchema.index({ user: 1, visitDate: -1 });
visitSchema.index({ doctor: 1, visitDate: -1 });
visitSchema.index({ monthYear: 1, user: 1 });
visitSchema.index({ status: 1, visitDate: -1 }); // Optimized for status + date queries
visitSchema.index({ visitDate: -1 });
visitSchema.index({ yearWeekKey: 1 });
visitSchema.index({ doctor: 1, user: 1, monthYear: 1 }); // For monthly visit count queries

/**
 * Calculate ISO 8601 week number
 * Week 1 is the first week with a Thursday (or the week containing January 4th)
 * @param {Date} date - The date to calculate week for
 * @returns {Object} - { weekNumber, weekYear } where weekYear may differ from calendar year
 */
function getISOWeek(date) {
  // Create a copy in UTC to avoid timezone issues
  const d = new Date(Date.UTC(date.getFullYear(), date.getMonth(), date.getDate()));

  // Set to nearest Thursday: current date + 4 - current day number
  // Make Sunday day 7 instead of 0
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);

  // Get first day of year
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));

  // Calculate full weeks to nearest Thursday
  const weekNumber = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);

  // The year for the ISO week might be different from calendar year
  // (e.g., Dec 31 might be in Week 1 of next year)
  const weekYear = d.getUTCFullYear();

  return { weekNumber, weekYear };
}

/**
 * 4-week cycle anchor: January 5, 2026 (Monday) = W1D1
 * Cycles repeat every 28 calendar days from this anchor.
 */
const CYCLE_ANCHOR = new Date(2026, 0, 5); // Jan 5, 2026

/**
 * Calculate cycle position based on the Jan 5, 2026 anchor.
 * @param {Date} date
 * @returns {{ weekInCycle: number, dayInCycle: number }}
 *   weekInCycle: 1-4, dayInCycle: 1-7 (1=Mon, 5=Fri, 6=Sat, 7=Sun)
 */
function getCyclePosition(date) {
  const diffMs = date.getTime() - CYCLE_ANCHOR.getTime();
  const diffDays = Math.floor(diffMs / 86400000);
  const dayInCycle = ((diffDays % 28) + 28) % 28; // 0-27, handles pre-anchor dates
  const weekInCycle = Math.floor(dayInCycle / 7) + 1; // 1-4
  const dayOfWeekInCycle = (dayInCycle % 7) + 1; // 1=Mon ... 7=Sun
  return { weekInCycle, dayOfWeekInCycle };
}

// Pre-save hook to generate week tracking fields
visitSchema.pre('save', function (next) {
  if (this.isNew || this.isModified('visitDate')) {
    const date = this.visitDate;

    // Get ISO week number (1-53) and week year
    const { weekNumber, weekYear } = getISOWeek(date);
    this.weekNumber = weekNumber;

    // Get anchor-based cycle position (W1-W4, D1-D7)
    const { weekInCycle, dayOfWeekInCycle } = getCyclePosition(date);
    this.weekOfMonth = weekInCycle;
    this.dayOfWeek = dayOfWeekInCycle;

    // Generate week label (W1D1, W2D3, etc.)
    this.weekLabel = `W${this.weekOfMonth}D${this.dayOfWeek}`;

    // monthYear = calendar month of the actual visit date
    const monthStr = String(date.getMonth() + 1).padStart(2, '0');
    this.monthYear = `${date.getFullYear()}-${monthStr}`;

    // Generate yearWeekKey using ISO week year (handles year boundaries correctly)
    // e.g., Dec 31, 2024 might be "2025-W01" if it falls in week 1 of 2025
    const week = String(weekNumber).padStart(2, '0');
    this.yearWeekKey = `${weekYear}-W${week}`;
  }
  next();
});

// Pre-save validation for work days only (Mon-Fri)
visitSchema.pre('save', function (next) {
  const jsDay = this.visitDate.getDay();
  if (jsDay === 0 || jsDay === 6) {
    return next(new Error('Visits can only be logged on work days (Monday-Friday)'));
  }
  next();
});

// Virtual: Check if this is today's visit
visitSchema.virtual('isToday').get(function () {
  const today = new Date();
  return (
    this.visitDate.getDate() === today.getDate() &&
    this.visitDate.getMonth() === today.getMonth() &&
    this.visitDate.getFullYear() === today.getFullYear()
  );
});

// Static: Get visits for a user in a specific month
visitSchema.statics.getMonthlyVisits = function (userId, monthYear) {
  return this.find({
    user: userId,
    monthYear: monthYear,
    status: 'completed',
  }).populate('doctor', 'firstName lastName specialization clinicOfficeAddress');
};

// Static: Get visits for a user in a specific week
visitSchema.statics.getWeeklyVisits = function (userId, yearWeekKey) {
  return this.find({
    user: userId,
    yearWeekKey: yearWeekKey,
    status: 'completed',
  }).populate('doctor', 'firstName lastName specialization clinicOfficeAddress');
};

// Static: Count visits to a doctor by a user in a month
visitSchema.statics.countDoctorVisitsInMonth = async function (doctorId, userId, monthYear) {
  return this.countDocuments({
    doctor: doctorId,
    user: userId,
    monthYear: monthYear,
    status: 'completed',
  });
};

// Static: Get weekOfMonth values for visits to a doctor by a user in a month
// Used by alternating week validation (2x frequency doctors must visit W1+W3 or W2+W4)
visitSchema.statics.getDoctorVisitWeeksInMonth = async function (doctorId, userId, monthYear) {
  const visits = await this.find({
    doctor: doctorId,
    user: userId,
    monthYear: monthYear,
    status: 'completed',
  }).select('weekOfMonth').lean();
  return visits.map((v) => v.weekOfMonth);
};

// Static: Check if user already visited doctor this week
visitSchema.statics.hasVisitedThisWeek = async function (doctorId, userId, yearWeekKey) {
  const visit = await this.findOne({
    doctor: doctorId,
    user: userId,
    yearWeekKey: yearWeekKey,
    status: 'completed',
  });
  return !!visit;
};

// Static: Get weekly compliance stats for a user
visitSchema.statics.getWeeklyComplianceStats = async function (userId, monthYear) {
  return this.aggregate([
    {
      $match: {
        user: new mongoose.Types.ObjectId(userId),
        monthYear: monthYear,
        status: 'completed',
      },
    },
    {
      $group: {
        _id: '$weekOfMonth',
        visitCount: { $sum: 1 },
        doctors: { $addToSet: '$doctor' },
      },
    },
    {
      $sort: { _id: 1 },
    },
  ]);
};

const Visit = mongoose.model('Visit', visitSchema);

module.exports = Visit;
