/**
 * Visit Model
 *
 * This model represents visits made by field employees to doctors
 *
 * Key features:
 * - Weekly visit enforcement: One visit per doctor per week (Mon-Fri)
 * - Required GPS location for proof of visit
 * - Required photo capture for verification
 * - Weekly tracking with W1D1, W2D3 format labels
 * - Hard limit on monthly quota (2x or 4x based on doctor's visitFrequency)
 */

const mongoose = require('mongoose');

const visitSchema = new mongoose.Schema(
  {
    // References
    doctor: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Doctor',
      required: [true, 'Doctor is required'],
    },
    user: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'User is required'],
    },

    // Visit timing
    visitDate: {
      type: Date,
      required: [true, 'Visit date is required'],
      default: Date.now,
    },
    visitType: {
      type: String,
      default: 'regular',
    }, // Lookup: VISIT_TYPE

    // Weekly tracking fields (critical for enforcement)
    // Note: These are auto-generated by pre-save hook, not required on input
    weekNumber: {
      type: Number,
      min: 1,
      max: 53,
    },
    weekOfMonth: {
      type: Number,
      min: 1,
      max: 5,
    },
    dayOfWeek: {
      type: Number,
      min: 1, // 1 = Monday
      max: 7, // 7 = Sunday (weekends now allowed conditionally)
    },
    weekLabel: {
      type: String, // "W1D1", "W2D3", etc.
    },
    monthYear: {
      type: String, // "2024-12"
    },
    yearWeekKey: {
      type: String, // "2024-W52" - ISO week format for unique constraint
    },

    // Weekend visit flag (for reporting)
    isWeekendVisit: {
      type: Boolean,
      default: false,
    },

    // Location (optional — attached when available for extra verification)
    location: {
      latitude: {
        type: Number,
      },
      longitude: {
        type: Number,
      },
      accuracy: {
        type: Number, // GPS accuracy in meters
      },
      capturedAt: {
        type: Date,
        default: Date.now,
      },
    },

    // Photos (REQUIRED - minimum 1, maximum 10 for proof of visit)
    photos: {
      type: [
        {
          url: { type: String, required: true }, // S3 URL
          capturedAt: { type: Date, required: true },
          source: { type: String, default: 'camera' }, // Lookup: PHOTO_SOURCE
          thumbnailUrl: { type: String },
          hash: { type: String }, // MD5 hash for duplicate detection
        },
      ],
      validate: {
        validator: function (arr) {
          return arr && arr.length >= 1 && arr.length <= 10;
        },
        message: 'Visits must have 1-10 photos as proof of visit',
      },
    },

    // Photo audit flags (for admin review)
    photoFlags: {
      type: [String], // Lookup: PHOTO_FLAG
      default: [],
    },
    photoFlagDetails: [
      {
        flag: { type: String }, // Lookup: PHOTO_FLAG
        photoIndex: { type: Number },
        detail: { type: String },
        matchedVisitId: { type: mongoose.Schema.Types.ObjectId },
        matchedVisitType: { type: String }, // vip | regular
      },
    ],

    // Products discussed during visit
    productsDiscussed: [
      {
        product: {
          type: mongoose.Schema.Types.ObjectId,
          ref: 'CrmProduct',
        },
        presented: { type: Boolean, default: true },
        feedback: { type: String },
      },
    ],

    // Engagement types (maps to Excel CPT day sheet columns G-K)
    engagementTypes: {
      type: [String],
      default: [],
    }, // Lookup: ENGAGEMENT_TYPE

    // Visit details
    purpose: {
      type: String,
      maxlength: [500, 'Purpose cannot exceed 500 characters'],
    },
    doctorFeedback: {
      type: String,
      maxlength: [1000, 'Feedback cannot exceed 1000 characters'],
    },
    notes: {
      type: String,
      maxlength: [1000, 'Notes cannot exceed 1000 characters'],
    },
    duration: {
      type: Number, // Duration in minutes
      min: 1,
      max: 480, // Max 8 hours
    },

    // Status tracking
    status: {
      type: String,
      enum: ['completed', 'cancelled'],
      default: 'completed',
    },
    cancelReason: {
      type: String,
      maxlength: [500, 'Cancel reason cannot exceed 500 characters'],
    },

    // Next visit scheduling
    nextVisitDate: {
      type: Date,
    },

    // ── Phase N — Offline Visit + CLM Merge linkage ─────────────────
    // Set when a Visit is created from VisitLogger's "Start Presentation" flow.
    // The CLM session is the "presentation half" of the same encounter; the
    // Visit row is the "compliance half". Linkage is bidirectional so admin
    // analytics can travel either direction without joining on a UUID.
    // Note: explicit sparse index declared below (visitSchema.index calls)
    clm_session_id: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'CLMSession',
    },
    // Client-generated UUID (matches CLMSession.idempotencyKey) used to
    // resolve the FK pair when CLM and Visit are submitted from offline
    // queue replay. The SW replays CLM first, Visit second; the Visit's
    // create handler looks up the CLMSession by this group_id and stamps
    // both halves of the pair before saving. Sparse index supports the
    // lookup without bloating storage for online-only visits.
    session_group_id: {
      type: String,
      trim: true,
      maxlength: 128,
    },
  },
  {
    timestamps: true,
    toJSON: { virtuals: true },
    toObject: { virtuals: true },
  }
);

// Compound index to enforce ONE visit per doctor per week per user
visitSchema.index(
  { doctor: 1, user: 1, yearWeekKey: 1 },
  {
    unique: true,
    partialFilterExpression: { status: 'completed' },
  }
);

// Other indexes for performance
visitSchema.index({ user: 1, visitDate: -1 });
visitSchema.index({ doctor: 1, visitDate: -1 });
visitSchema.index({ monthYear: 1, user: 1 });
visitSchema.index({ status: 1, visitDate: -1 }); // Optimized for status + date queries
visitSchema.index({ visitDate: -1 });
visitSchema.index({ yearWeekKey: 1 });
visitSchema.index({ doctor: 1, user: 1, monthYear: 1 }); // For monthly visit count queries
visitSchema.index({ doctor: 1, user: 1, monthYear: 1, status: 1 }); // For filtered monthly count queries
visitSchema.index({ 'photos.hash': 1 }, { sparse: true }); // For duplicate photo detection
visitSchema.index({ photoFlags: 1 }, { sparse: true }); // For photo audit queries
// Phase N — sparse so online-only visits don't bloat the index
visitSchema.index({ clm_session_id: 1 }, { sparse: true });
visitSchema.index({ session_group_id: 1 }, { sparse: true });

/**
 * Calculate ISO 8601 week number
 * Week 1 is the first week with a Thursday (or the week containing January 4th)
 * @param {Date} date - The date to calculate week for
 * @returns {Object} - { weekNumber, weekYear } where weekYear may differ from calendar year
 */
function getISOWeek(date) {
  // Create a copy in UTC to avoid timezone issues (date is already Manila-adjusted, use UTC methods)
  const d = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth(), date.getUTCDate()));

  // Set to nearest Thursday: current date + 4 - current day number
  // Make Sunday day 7 instead of 0
  const dayNum = d.getUTCDay() || 7;
  d.setUTCDate(d.getUTCDate() + 4 - dayNum);

  // Get first day of year
  const yearStart = new Date(Date.UTC(d.getUTCFullYear(), 0, 1));

  // Calculate full weeks to nearest Thursday
  const weekNumber = Math.ceil(((d - yearStart) / 86400000 + 1) / 7);

  // The year for the ISO week might be different from calendar year
  // (e.g., Dec 31 might be in Week 1 of next year)
  const weekYear = d.getUTCFullYear();

  return { weekNumber, weekYear };
}

/**
 * 4-week cycle anchor: January 5, 2026 (Monday) = W1D1
 * Cycles repeat every 28 calendar days from this anchor.
 */
const CYCLE_ANCHOR = new Date(Date.UTC(2026, 0, 5)); // Jan 5, 2026 (UTC)
const MANILA_OFFSET_MS = 8 * 60 * 60 * 1000; // UTC+8 (Asia/Manila)

/**
 * Calculate cycle position based on the Jan 5, 2026 anchor.
 * Uses Manila time (UTC+8) so midnight visits in the Philippines get the correct day/week.
 * @param {Date} date
 * @returns {{ weekInCycle: number, dayOfWeekInCycle: number }}
 *   weekInCycle: 1-4, dayOfWeekInCycle: 1-7 (1=Mon, 5=Fri, 6=Sat, 7=Sun)
 */
function getCyclePosition(date) {
  // Shift to Manila time so UTC-midnight visits (which are ~8h behind Manila) resolve correctly
  const manilaDate = new Date(date.getTime() + MANILA_OFFSET_MS);
  const diffMs = manilaDate.getTime() - CYCLE_ANCHOR.getTime();
  const diffDays = Math.floor(diffMs / 86400000);
  const dayInCycle = ((diffDays % 28) + 28) % 28; // 0-27
  const weekInCycle = Math.floor(dayInCycle / 7) + 1; // 1-4
  const jsDay = manilaDate.getUTCDay(); // Use UTC methods on Manila-adjusted date
  const dayOfWeekInCycle = jsDay === 0 ? 7 : jsDay; // 1=Mon ... 7=Sun
  return { weekInCycle, dayOfWeekInCycle };
}

// Pre-save hook to generate week tracking fields
visitSchema.pre('save', function (next) {
  if (this.isNew || this.isModified('visitDate')) {
    const date = this.visitDate;
    // Use Manila time for all calendar calculations (UTC+8)
    const manilaDate = new Date(date.getTime() + MANILA_OFFSET_MS);

    // Get ISO week number (1-53) and week year — pass Manila-adjusted date
    const { weekNumber, weekYear } = getISOWeek(manilaDate);
    this.weekNumber = weekNumber;

    // Get anchor-based cycle position (W1-W4, D1-D7)
    const { weekInCycle, dayOfWeekInCycle } = getCyclePosition(date);
    this.weekOfMonth = weekInCycle;
    this.dayOfWeek = dayOfWeekInCycle;

    // Generate week label (W1D1, W2D3, etc.)
    this.weekLabel = `W${this.weekOfMonth}D${this.dayOfWeek}`;

    // monthYear = Manila calendar month of the visit date
    const monthStr = String(manilaDate.getUTCMonth() + 1).padStart(2, '0');
    this.monthYear = `${manilaDate.getUTCFullYear()}-${monthStr}`;

    // Generate yearWeekKey using ISO week year
    const week = String(weekNumber).padStart(2, '0');
    this.yearWeekKey = `${weekYear}-W${week}`;

    // Set weekend flag using Manila day
    const jsDay = manilaDate.getUTCDay();
    this.isWeekendVisit = jsDay === 0 || jsDay === 6;
  }
  next();
});

// Virtual: Check if this is today's visit
visitSchema.virtual('isToday').get(function () {
  const today = new Date();
  return (
    this.visitDate.getDate() === today.getDate() &&
    this.visitDate.getMonth() === today.getMonth() &&
    this.visitDate.getFullYear() === today.getFullYear()
  );
});

// Static: Get visits for a user in a specific month
visitSchema.statics.getMonthlyVisits = function (userId, monthYear) {
  return this.find({
    user: userId,
    monthYear: monthYear,
    status: 'completed',
  }).populate('doctor', 'firstName lastName specialization clinicOfficeAddress locality province');
};

// Static: Get visits for a user in a specific week
visitSchema.statics.getWeeklyVisits = function (userId, yearWeekKey) {
  return this.find({
    user: userId,
    yearWeekKey: yearWeekKey,
    status: 'completed',
  }).populate('doctor', 'firstName lastName specialization clinicOfficeAddress locality province');
};

// Static: Count visits to a doctor by a user in a month
visitSchema.statics.countDoctorVisitsInMonth = async function (doctorId, userId, monthYear) {
  return this.countDocuments({
    doctor: doctorId,
    user: userId,
    monthYear: monthYear,
    status: 'completed',
  });
};

// Static: Get weekOfMonth values for visits to a doctor by a user in a month
// Used by alternating week validation (2x frequency doctors must visit W1+W3 or W2+W4)
visitSchema.statics.getDoctorVisitWeeksInMonth = async function (doctorId, userId, monthYear) {
  const visits = await this.find({
    doctor: doctorId,
    user: userId,
    monthYear: monthYear,
    status: 'completed',
  }).select('weekOfMonth').lean();
  return visits.map((v) => v.weekOfMonth);
};

// Static: Check if user already visited doctor this week
visitSchema.statics.hasVisitedThisWeek = async function (doctorId, userId, yearWeekKey) {
  const visit = await this.findOne({
    doctor: doctorId,
    user: userId,
    yearWeekKey: yearWeekKey,
    status: 'completed',
  });
  return !!visit;
};

// Static: Get weekly compliance stats for a user
visitSchema.statics.getWeeklyComplianceStats = async function (userId, monthYear) {
  return this.aggregate([
    {
      $match: {
        user: new mongoose.Types.ObjectId(userId),
        monthYear: monthYear,
        status: 'completed',
      },
    },
    {
      $group: {
        _id: '$weekOfMonth',
        visitCount: { $sum: 1 },
        doctors: { $addToSet: '$doctor' },
      },
    },
    {
      $sort: { _id: 1 },
    },
  ]);
};

const Visit = mongoose.model('Visit', visitSchema);

module.exports = Visit;
